name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgl1-mesa-glx

    - name: Install Python dependencies
      run: |
        pip install -r requirements.txt

    - name: Install PyTorch
      run: |
        pip install torch==1.12.1 torchvision==0.13.1 torchaudio==0.12.1

    - name: Install MMCV and MMGeneration
      run: |
        pip install -U openmim
        mim install mmcv-full==1.6
        git clone https://github.com/open-mmlab/mmgeneration && cd mmgeneration && git checkout v0.7.2
        pip install -v -e .
        cd ..

    - name: Check import
      run: |
        python -c "import ssdnerf"