name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgl1-mesa-glx

    - name: Install Python dependencies
      run: |
        pip install -r requirements.txt

    - name: Install PyTorch
      run: |
        pip install torch torchvision torchaudio

    - name: Install MMCV
      run: |
        pip install mmcv-full

    - name: Run train.py
      run: |
        python train.py